# Generated by Django 6.0.dev20250725051842 on 2025-07-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "budget_type",
                    models.CharField(
                        choices=[("Income", "Income"), ("Expense", "Expense")]
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("month", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
