# Generated by Django 6.0.dev20250725051842 on 2025-07-30 23:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0002_budgetcategory_monthlybudget_delete_budget"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="budgetcategory",
            old_name="name",
            new_name="category",
        ),
        migrations.AlterUniqueTogether(
            name="budgetcategory",
            unique_together={("user", "category")},
        ),
    ]
